# fly.toml app configuration file generated for xblack-bot on 2026-05-25T21:58:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "xblack-bot"
primary_region = "cdg"

[build]

[env]
PORT = "8080"

[http_service]
internal_port = 8080
force_https = true
auto_start_machines = true
auto_stop_machines = false
min_machines_running = 1

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1
